behaviors:
  Behavior01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      beta: 1.0e-2
      buffer_size: 20480
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      num_epoch: 1
    network_settings:
      hidden_units: 512
      normalize: true
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 512
        sequence_length: 32
    keep_checkpoints: 60
    checkpoint_interval: 500000
    max_steps: 30e6
    summary_freq: 10000
    time_horizon: 64
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 128
            learning_rate: 3.0e-4
        gail:
          strength: 0.01
          gamma: 0.99
          encoding_size: 128
          demo_path: Y:\RL-CargoManagement\Demos\DemoCurriculum_7.demo
          learning_rate: 3.0e-4
          use_actions: false
          use_vail: false
engine_settings:
  time_scale: 20
  no_graphics: true
debug: false
environment_parameters:
  cargo_variables:
    curriculum:
      - name: cargo_variables0
        completion_criteria:
          measure: progress
          behavior: Behavior01
          signal_smoothing: true
          threshold: 0.1
        value: 0.0
      - name: cargo_variables1
        completion_criteria:
          measure: progress
          behavior: Behavior01
          signal_smoothing: true
          threshold: 0.15
        value: 1.0
      - name: cargo_variables2
        completion_criteria:
          measure: progress
          behavior: Behavior01
          signal_smoothing: true
          threshold: 0.3
        value: 2.0
      - name: cargo_variables3
        completion_criteria:
          measure: progress
          behavior: Behavior01
          signal_smoothing: true
          threshold: 0.4
        value: 3.0
      - name: cargo_variables4
        completion_criteria:
          measure: progress
          behavior: Behavior01
          signal_smoothing: true
          threshold: 0.5
        value: 4.0
      - name: cargo_variables5
        value: 5.0
  agent_period:
    curriculum:
      - name: agent_period0
        completion_criteria:
          measure: reward
          behavior: Behavior01
          signal_smoothing: true
          min_lesson_length : 10000
          threshold: -0.2
        value: 50.0
      - name: agent_period1
        completion_criteria:
          measure: reward
          behavior: Behavior01
          signal_smoothing: true
          min_lesson_length : 10000
          threshold: 0
        value: 40.0
      - name: agent_period2
        completion_criteria:
          measure: reward
          behavior: Behavior01
          signal_smoothing: true
          min_lesson_length : 10000
          threshold: 0.2
        value: 30.0
      - name: agent_period3
        completion_criteria:
          measure: reward
          behavior: Behavior01
          signal_smoothing: true
          min_lesson_length : 10000
          threshold: 0.5
        value: 25.0
      - name: agent_period4
        completion_criteria:
          measure: reward
          behavior: Behavior01
          signal_smoothing: true
          min_lesson_length : 10000
          threshold: 0.8
        value: 20.0
      - name: agent_period5
        value: 15.0